'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Members', [
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'sara',
      facebookUrl: 'https://www.facebook.com/SaraMigoya',
      instagramUrl: 'https://www.instagram.com/SaraMigoya',
      linkedinUrl: 'https://www.linkedin.com/SaraMigoya',
      image: 'https://www.facebook.com/SaraMigoya',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Claudia',
      facebookUrl: 'https://www.facebook.com/ClaudiaFernandez',
      instagramUrl: 'https://www.instagram.com/ClaudiaFernandez',
      linkedinUrl: 'https://www.linkedin.com/ClaudiaFernandez',
      image: 'https://www.facebook.com/ClaudiaFernandez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Diego',
      facebookUrl: 'https://www.facebook.com/DiegoGonzalez',
      instagramUrl: 'https://www.instagram.com/DiegoGonzalez',
      linkedinUrl: 'https://www.linkedin.com/DiegoGonzalez',
      image: 'https://www.facebook.com/DiegoGonzalez',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    },
      {
      name: 'Julia',
      facebookUrl: 'https://www.facebook.com/JuliaMartin',
      instagramUrl: 'https://www.instagram.com/JuliaMartin',
      linkedinUrl: 'https://www.linkedin.com/JuliaMartin',
      image: 'https://www.facebook.com/JuliaMartin',
      description:'ONG-Somos más member', 
      createdAt: new Date,
      updatedAt: new Date,
    }
  
  ], {});
  },

  down: (queryInterface, Sequelize) => {

  }
};
